### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by jmodrako** [exoego/scala-js-nodejs#511]
Is it possible to use this library in the Scala 3 project?

**Comment by exoego** [comment]
I do not use this with Scala 3, but I guess it works with Scala 3 with `CrossVersion.for3Use2_13` 
Ref. https://www.scala-lang.org/blog/2021/04/08/scala-3-in-sbt.html

And since this library is manually modified, there might be mistakes.

I recommend https://github.com/ScalablyTyped.
It has type definitions for Node.js and tons of other npm mpdiles. 
Machine-generated so less likely to have errors.
